##YAML 规则
#属性值为普通数据类型直接配置属性值，字符串不需要写引号

server:
  port: 8080

#服务的名称
spring:
  application:
    name: Spring Boot CORE

##自定义属性用于测试
project:
  name: Demo for Spring Boot
  version: 0.0.1
  author:
    name: PNZ.BeijingL
    from: StarCraft PNZ TEAM
